apiVersion: v1
kind: Pod
metadata:
  name: gcs-workload-identity-test
  namespace: default
spec:
  containers:
  - image: gcr.io/cloud-builders/gsutil
    name: workload-identity-test
    command: ["sleep","infinity"]
  serviceAccountName: witest
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"
